### ISSUE TITLE
NodeMCU configuration

### ISSUE THREAD

**Issue by kasvith** [alentar/mediot-hardware#1]
# Problem

NodeMCU should be configured before using the actual web server provided by **mediot**.
This requires achieving followings

- Setup a prefered **SSID** and **Password**  for NodeMCU
- Setup provided Server Url(preferably for **HOST_URI**) by staff

# Solution

These items need to be saved on NodeMCU for continue process.
When you successfully connected to a WiFi NodeMCU will automatically save them in storage and when it restarts it will use previous credentials.

So it only requires to store **HOST_URI** itself on the **EEPROM**. Others are take care by **WiFi** module of **NodeMCU**.

So its required a way to start the Hotspot(aka AccessPoint or AP) of the NodeMCU. Preferably using a **Button**.

## Workflow of Proposed Solution

- Power on NodeMCU
- **Press Button** to **Start Configuration Mode**
- Password and SSID of this Hotspot is given to Staff
- The hotspot will start a simple webserver(RESTful) on **192.168.4.1**
- Staff will use an App after connecting this Hotspot and it will look for **192.168.4.1**.
- Once connected user can set above information with server
- Once finished User may exit Configuration Mode by selecting **Finish** on the App
- This may trigger NoduMCU to stop AccessPoint mode and try to connect given SSID and then send HTTP requests for **HOST_URI** (which set by user)
- Once connected the NodeMCU should show the status of the connection by indicating via LED so staff knows whether setup was successful

# Requirement
- NodeMCU with AccessPoint Mode
- For development purposes use **PostMan**
- NodeMCU should have a field called **SerialNo** which is used by server to provision the device.

**Comment by kasvith** [comment]
@edussuriyac @namila007 any comments ?

**Comment by kasvith** [comment]
Refer my code for webserver

**Comment by namila007** [comment]
starting working on this now . first i have to look up more details about this
